#!/bin/bash
check_even () {
	local mod=2
	echo “Value of mod is $mod inside func”

	if [$((“$1” % $mod)) -eq 0]
	then
		echo “The number $1 is even!”
	else
		echo “The number $1 is odd!” 
	fi
}

number=2344

check_even $number
echo $mod 	
